2024-12-28 23:36:50,191 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\MankoKS\pythonlesson\module12\tests_12_4.py", line 20, in test_run
    runner2 = Runner(33)
              ^^^^^^^^^^
  File "C:\Users\MankoKS\pythonlesson\module12\module12_log.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-28 23:36:50,193 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\MankoKS\pythonlesson\module12\tests_12_4.py", line 11, in test_walk
    runner1 = Runner('Nik', -8)
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\MankoKS\pythonlesson\module12\module12_log.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -8
